[package]
name = "mabandit"
version = "0.1.0"
authors = ["tmrob <tmrob2@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = { version = "2.33.3", features = ["yaml"]}
rand_distr = "0.4.1"
rand = "0.8.4"
